#!/bin/sh
PATH="/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Select action on shutdown: reboot or halt
touch /etc/runit/reboot
chmod 100 /etc/runit/reboot

# Select action: shutdown or not
touch /etc/runit/stopit
chmod 100 /etc/runit/stopit
